modLoader = "javafml"
loaderVersion = "[14,)"
updateJSONURL = "https://raw.githubusercontent.com/TheRandomLabs/RandomPatches/misc/versions.json"
issueTrackerURL = "https://github.com/TheRandomLabs/RandomPatches/issues"
displayURL = "https://minecraft.curseforge.com/projects/randompatches"
logoFile = "logo.png"
authors = "TheRandomLabs"

[[mods]]

modId = "randompatches"
version = "${file.jarVersion}"
displayName = "RandomPatches"
description = '''
RandomPatches, a bunch of miscellaneous patches for Minecraft.
'''
