modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheRandomLabs/RandomPatches/issues"

[[mods]]
modId = "randompatches"
version = "${file.jarVersion}"
displayName = "RandomPatches"
updateJSONURL = "https://raw.githubusercontent.com/TheRandomLabs/RandomPatches/misc/versions.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/randompatches-forge"
logoFile = "logo.png"
authors = "TheRandomLabs"
description = '''
RandomPatches, a bunch of miscellaneous patches for Minecraft.
'''

[[dependencies.randompatches]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,1.17)"
ordering = "NONE"
side = "BOTH"
